#!/bin/bash

# i3-config-gen <directory> [output file]
print_help ()
{
    echo "$0 <directory> [output file]"
}

if [[ $# -ge 1 ]]; then
    dir=$1
    out=./config
    if [[ $# -ge 2 ]]; then
        out=$2
    fi
else
    echo "Please provide a directory" 2>&1
    print_help 2>&1
    exit 1
fi

cat <(echo "# i3 config file (v4)")\
    "$dir/theme.config"\
    "$dir/monitors.config"\
    "$dir/workspaces.config"\
    "$dir/control.config"\
    "$dir/local.config"\
    "$dir/bar.config"\
    "$dir/startup.config"\
    > "$out"
